### PR TITLE
Implement dart builder

### PR DESCRIPTION
**Pull request by szotp**
As discussed in #1

### CODE REVIEW

**Comment by timfreiheit** [comment]
looks good and works mostly as expected.
It should be mentioned in the README that all assets have to be placed inside of the `lib` folder to make regenerating the `assets.dart` possible.
This should be adjusted for the fonts as well in the example.
From what I read in the documentation it should not be a problem to have assets inside of the lib folder.

**Comment by szotp** [comment]
Updated as requested.

**Comment by timfreiheit** [comment]
thank you very much for your hard work.
I will release this version as the version `0.2` to `pub.dev`

**Comment by szotp** [comment]
Cool, thanks. I just realized readme contains references to my fork, please change these before publishing.

**Pull request merged**
