### PR TITLE
Add support for i18n features

### PR DESCRIPTION
**Pull request by kostadin-damyanov-prime**
This PR adds support for organising intl strings by feature. See the README file on how to do that. This functionality is completely optional and it should keep backwards compatibility with the previous versions of r_flutter.

### CODE REVIEW

**Comment by kostadin-damyanov-prime** [comment]
@timfreiheit feedback is welcome :)

**Comment by timfreiheit** [comment]
@kostadin-damyanov-prime 
Looks nice but there is a bug when having languages in the base folder which are not available in a feature.

for example when adding a feature to the example project which only contains `de` and `en` variations like `pl` are generated incorrectly:

```
@override
I18nFeatureLookup_pl createFeatureLookup() => I18nFeatureLookup_pl();
```

The feature locales should be independent from each other to avoid this kind of conflicts.
I guess each feature needs it own `_findLookUpFromLocale` implementation

**Comment by kostadin-damyanov-prime** [comment]
Oh yes, you are right. Good catch.
Maybe in this case it will be easier to just not generate the `createXLookup()` methods?

Note the commented out code, it will not be generated:

```dart
class I18nLookup_pl extends I18nLookup_de {
  @override
  String get hello {
    return "hello";
  }

  @override
  String get world {
    return "world";
  }

  // @override
  // I18nHomeLookup_pl createHomeLookup() => I18nHomeLookup_pl();
  //
  // @override
  // I18nAnnouncementsLookup_pl createAnnouncementsLookup() => I18nAnnouncementsLookup_pl();
}
```

Since the class already extends `I18nLookup_de` it will fall back to the default lookup table (assuming `de` is set as the primary language in pubspec.yaml).

**Comment by timfreiheit** [comment]
Not generating the `createXLookup` would work. but only in cases where the featureless translations contain all locales right?
In cases where a feature contains more locales they would get ignored right?

**Comment by kostadin-damyanov-prime** [comment]
I just tested it and created a `home/ro.arb` with no main translation for `ro`.

The following class got generated but it is not referenced anywhere.

```dart
class I18nHomeLookup_ro extends I18nHomeLookup_en {
  @override
  String get title {
    return "Home Screen ro";
  }

  @override
  String get welcome {
    return "Welcome to home screen ro";
  }
}
```

It is not needed so it should not be generated at all.
So the following changes are needed:
- stop generating `createXLookup()` methods for featureless translations
- stop generating lookup classes for extra translations in the feature folders like in the example above

Correct?

**Comment by timfreiheit** [comment]
When there is a translation file `home/ro.arb` it should also be used, even when the main translation does not contain `ro`.
Using the feature translations it sounds like developers might not want to use the main translations at all and could only use feature based translations for the app.

**Comment by kostadin-damyanov-prime** [comment]
@timfreiheit Well, in our project we still use primary translations for "general purpose" strings like yes, no, cancel, edit, delete, create, send etc. They do not belong to any specific feature so it is quite useful.

Regardless, I added some changes to support both cases you described:
- featureless translations now do not generate the 'createXLookup' method
- feature-only translations also get a primary translation

**Comment by timfreiheit** [comment]
@kostadin-damyanov-prime Looks good. thank you.
I will upload a new version of the package later today

**Pull request merged**
