### PR TITLE
Add comments flag to pubspec configs

### PR DESCRIPTION
**Pull request by KhaleelSH**
This flag `add_file_path_comments` would allow the user to decide if they want the file path comments or not.
This is because when working in a team using multiple machines, there is no use of these comments.
```
  /// ![](file:///Users/khaleel/my_app/assets/svg/img.svg)
```

### CODE REVIEW

**Comment by timfreiheit** [comment]
generated files should not be put into source control to avoid this kind of problems. Every of your team members should generate the files on their own

**Comment by KhaleelSH** [comment]
Well, I believe there are pros and cons for adding or ignoring generated files from source control. But at least, devs should have the option to decide what's the best for their team.
https://beltran.work/blog/should-i-add-generated-dart-files-to-git/

**Comment by timfreiheit** [comment]
Alright. Having an option in this case should not be a problem.
Please add tests which cover this feature

**Comment by KhaleelSH** [comment]
Added. @timfreiheit

**Pull request merged**
